name: sponge_grpc_client_dart
version: 1.13.0

description: Sponge gRPC client for Dart. It simplifies connecting to a remote Sponge gRPC service.
author: The Sponge Team <sponge_team@softelnet.com>
homepage: https://github.com/softelnet/sponge_grpc_client_dart

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  grpc: ^2.1.2
  protobuf: ^0.13.15
  sync: ^0.2.0
  logging: ^0.11.3+2
  sponge_client_dart: ^1.13.0 # Uncomment for publishing.
    #path: ../sponge_client_dart # Use the local library if possible. Comment for publishing.

dev_dependencies:
  test: ^1.9.3
  pedantic: ^1.8.0+1
